// <auto-generated />
using System;
using ExpoConnect.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExpoConnect.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "visit_sticker", new[] { "innovative", "professional", "friendly", "informative", "high_quality", "good_value", "impressive", "would_recommend" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExpoConnect.Domain.Auth.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("text")
                        .HasColumnName("replaced_by_token");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_auth_refresh_token");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_auth_refresh_token_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_auth_refresh_token_user_id");

                    b.ToTable("auth_refresh_token", (string)null);
                });

            modelBuilder.Entity("ExpoConnect.Domain.Auth.UserCredential", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("UserId")
                        .HasName("pk_user_credentials");

                    b.ToTable("user_credentials", (string)null);
                });

            modelBuilder.Entity("ExpoConnect.Domain.Expo.Catalog", b =>
                {
                    b.Property<Guid>("CatalogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("catalog_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("StandId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasColumnName("stand_id");

                    b.HasKey("CatalogId")
                        .HasName("pk_catalogs");

                    b.HasIndex("StandId")
                        .HasDatabaseName("ix_catalogs_stand_id");

                    b.ToTable("catalogs", (string)null);
                });

            modelBuilder.Entity("ExpoConnect.Domain.Expo.CatalogItem", b =>
                {
                    b.Property<Guid>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("item_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("CatalogId")
                        .HasColumnType("uuid")
                        .HasColumnName("catalog_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string[]>("Features")
                        .HasColumnType("text[]")
                        .HasColumnName("features");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price");

                    b.HasKey("ItemId")
                        .HasName("pk_catalog_item");

                    b.HasIndex("CatalogId")
                        .HasDatabaseName("ix_catalog_item_catalog_id");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_catalog_item_category");

                    b.HasIndex("CatalogId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_catalog_item_catalog_id_name");

                    b.ToTable("catalog_item", (string)null);
                });

            modelBuilder.Entity("ExpoConnect.Domain.Expo.Stand", b =>
                {
                    b.Property<string>("QrCode")
                        .HasMaxLength(128)
                        .HasColumnType("varchar")
                        .HasColumnName("qr_code");

                    b.Property<string>("BannerUrl")
                        .HasColumnType("text")
                        .HasColumnName("banner_url");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar")
                        .HasColumnName("company_name");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("varchar")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(30)
                        .HasColumnType("varchar")
                        .HasColumnName("contact_phone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ExhibitorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("exhibitor_id");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("industry");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<string>("StandNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("stand_number");

                    b.Property<string>("Website")
                        .HasColumnType("text")
                        .HasColumnName("website");

                    b.HasKey("QrCode")
                        .HasName("pk_stand");

                    b.HasIndex("ExhibitorId")
                        .HasDatabaseName("ix_stand_exhibitor_id");

                    b.HasIndex("StandNumber")
                        .HasDatabaseName("ix_stand_stand_number");

                    b.ToTable("stand", (string)null);
                });

            modelBuilder.Entity("ExpoConnect.Domain.Expo.Visit", b =>
                {
                    b.Property<Guid>("VisitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("visit_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("FollowUp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bool")
                        .HasDefaultValue(false)
                        .HasColumnName("follow_up");

                    b.Property<bool>("IsFavorite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bool")
                        .HasDefaultValue(false)
                        .HasColumnName("is_favorite");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int?>("Rating")
                        .HasColumnType("int4")
                        .HasColumnName("rating");

                    b.Property<string>("StandId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar")
                        .HasColumnName("stand_id");

                    b.Property<int[]>("Stickers")
                        .HasColumnType("visit_sticker[]")
                        .HasColumnName("stickers");

                    b.Property<string>("VisitorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("visitor_id");

                    b.HasKey("VisitId")
                        .HasName("pk_visit");

                    b.HasIndex("Rating")
                        .HasDatabaseName("ix_visit_rating");

                    b.HasIndex("StandId")
                        .HasDatabaseName("ix_visit_stand_id");

                    b.HasIndex("VisitorId")
                        .HasDatabaseName("ix_visit_visitor_id");

                    b.HasIndex("VisitorId", "StandId")
                        .IsUnique()
                        .HasDatabaseName("ix_visit_visitor_id_stand_id");

                    b.ToTable("visit", (string)null);
                });

            modelBuilder.Entity("ExpoConnect.Domain.Users.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("Company")
                        .HasMaxLength(200)
                        .HasColumnType("varchar")
                        .HasColumnName("company");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bool")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("varchar")
                        .HasColumnName("phone");

                    b.Property<DateTime?>("RefreshTokenExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expires_at_utc");

                    b.Property<string>("RefreshTokenHash")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("UserId")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_users_is_active");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_users_role");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ExpoConnect.Domain.Auth.RefreshToken", b =>
                {
                    b.HasOne("ExpoConnect.Domain.Users.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_refresh_token_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExpoConnect.Domain.Auth.UserCredential", b =>
                {
                    b.HasOne("ExpoConnect.Domain.Users.User", null)
                        .WithOne("Credential")
                        .HasForeignKey("ExpoConnect.Domain.Auth.UserCredential", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_credentials_users_user_id");
                });

            modelBuilder.Entity("ExpoConnect.Domain.Expo.Catalog", b =>
                {
                    b.HasOne("ExpoConnect.Domain.Expo.Stand", "Stand")
                        .WithMany("Catalog")
                        .HasForeignKey("StandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_catalog_stand");

                    b.Navigation("Stand");
                });

            modelBuilder.Entity("ExpoConnect.Domain.Expo.CatalogItem", b =>
                {
                    b.HasOne("ExpoConnect.Domain.Expo.Catalog", "Catalog")
                        .WithMany("Items")
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_catalog_item_catalog");

                    b.Navigation("Catalog");
                });

            modelBuilder.Entity("ExpoConnect.Domain.Expo.Stand", b =>
                {
                    b.HasOne("ExpoConnect.Domain.Users.User", "Exhibitor")
                        .WithMany()
                        .HasForeignKey("ExhibitorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stand_users");

                    b.Navigation("Exhibitor");
                });

            modelBuilder.Entity("ExpoConnect.Domain.Expo.Visit", b =>
                {
                    b.HasOne("ExpoConnect.Domain.Expo.Stand", "Stand")
                        .WithMany()
                        .HasForeignKey("StandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_visit_stand");

                    b.HasOne("ExpoConnect.Domain.Users.User", "Visitor")
                        .WithMany()
                        .HasForeignKey("VisitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_visit_users");

                    b.Navigation("Stand");

                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("ExpoConnect.Domain.Expo.Catalog", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ExpoConnect.Domain.Expo.Stand", b =>
                {
                    b.Navigation("Catalog");
                });

            modelBuilder.Entity("ExpoConnect.Domain.Users.User", b =>
                {
                    b.Navigation("Credential");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
